name: BetterSleep
options:
  bundleIdPrefix: com.example
targets:
  BetterSleep:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources:
      - Sources/BetterSleep
    frameworks:
      - AVFoundation
      - CoreML
      - Speech
      - HealthKit
      - CoreAudioTypes
      - SwiftUI
    infoPlist:
      path: Sources/BetterSleep/Info.plist